version: '3'
services:
    ia.cidada.api:
        build: .
        container_name: ia-cidada-api
        image: gcr.io/ia-cidada/api:latest
        tty: true
        working_dir: /app
        ports:
           - 8080:8080
        volumes:
            - ./:/app
