version: '3'
services:
    #ia.cidada.api:
    #    build: .
    #    container_name: ia-cidada-api
    #    tty: true
    #    working_dir: /var/www
    #    ports:
    #        - 5000:5000
    #    volumes:
    #        - ./:/var/www
    ia.cidada.mongo:
        container_name: ia.cidada.mongo
        image: mongo
        restart: always
        volumes:
        - ./.datadb:/data/db
        ports:
        - 27017:27017
        command: ["--auth", "--storageEngine", "wiredTiger"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: abc123
